from jinja2 import Template
import logging

logger = logging.getLogger(__name__)


def build_report(resources, total_cost, violations, scan_errors=None, delivery_errors=None):
    """Build formatted Markdown report from scan results."""
    scan_errors = scan_errors or []
    delivery_errors = delivery_errors or []
    
    logger.info(f"Building report with {len(resources)} resources, {len(violations)} violations")
    
    template = Template("""
# AWS Waste Hunter — Weekly Cost Optimization Report

## Summary
**Total Monthly Waste:** ${{ total_cost }}
**Resources Found:** {{ resources|length }}
**Tag Violations:** {{ violations|length }}
**Scan Errors:** {{ scan_errors|length }}
**Delivery Errors:** {{ delivery_errors|length }}

## Wasted Resources
{% for r in resources %}
- **{{ r.type }}{% if r.lb_type %} ({{ r.lb_type }}){% endif %} {{ r.id }}**{% if r.avg_cpu %} - CPU: {{ r.avg_cpu }}%{% endif %}{% if r.instance_type %} - {{ r.instance_type }}{% endif %}{% if r.instance_class %} - {{ r.instance_class }}{% endif %}
  - Location: {{ r.az }}{% if r.region %} ({{ r.region }}){% endif %}
  - Cost: ${{ r.monthly_cost }}/month
{% endfor %}
{% if resources|length == 0 %}
- None detected
{% endif %}

## Tagging Violations
{% for v in violations %}
- **{{ v.type }} {{ v.resource_id }}** 
  - Missing tags: {{ v.missing_tags|join(', ') }}
  {% if v.tags %}
  - Existing tags: {{ v.tags.keys()|list|join(', ') }}
  {% endif %}
{% endfor %}
{% if violations|length == 0 %}
- None detected
{% endif %}

## Scan/Delivery Errors
{% for e in scan_errors %}
- **Scan failure** in {{ e.stage }}
  - Error: {{ e.error }}
  {% if e.type %}
  - Type: {{ e.type }}
  {% endif %}
{% endfor %}
{% for e in delivery_errors %}
- **Delivery failure** in {{ e.stage }}
  - Error: {{ e.error }}
  {% if e.type %}
  - Type: {{ e.type }}
  {% endif %}
{% endfor %}
{% if scan_errors|length == 0 and delivery_errors|length == 0 %}
- None
{% endif %}

## Recommended Actions
- **EBS volumes:** Delete unattached volumes or create snapshots first
- **EC2 instances:** Stop or downsize idle instances, notify owners
- **Load Balancers:** Remove unused ALB/NLB/Classic LBs
- **RDS:** Take snapshots then delete stopped clusters/instances
- **Tags:** Fix missing tags for cost attribution and ownership
- **Errors:** Review scan/delivery errors above and check IAM permissions

---
*Report generated by AWS Waste Hunter*
""")

    try:
        return template.render(
            resources=resources,
            total_cost=total_cost,
            violations=violations,
            scan_errors=scan_errors,
            delivery_errors=delivery_errors,
        )
    except Exception as e:
        logger.error(f"Error rendering report template: {e}", exc_info=True)
        raise
